logo: "assets/logo.png"

meta:
  company_name: Awesome Corp.
  company_legal_entity: Awesome Corp, LLC
  tagline: Simple Budgeting & Personal Finance Software
  description: >- # this means to ignore newlines until "baseurl:"
    Trusted by millions, Basecamp puts everything you need to get work done in one
    place. It’s the calm, organized way to manage projects, work with clients, and
    communicate company-wide.

seo:
  image_path: "assets/social-image.png"

contacts:
  general: email@example.com
  support: support@example.com
  feedback: feedback@example.com
